app:
  APP_NAME: SHOP
  APP_ENV: local
  APP_DEBUG: true
  APP_URL: http://localhost:8088
  APP_LOG_LEVEL: debug
  APP_PORT: 8088
mysql:
  DB_CONNECTION: mysql
  DB_HOST: 127.0.0.1
  DB_PORT: 3306
  DB_DATABASE: shop
  DB_USERNAME: root
  DB_PASSWORD: root
